language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"
  - "pypy"
  - "pypy3"
cache:
  directories:
    - $HOME/noaadem
    - bin
    - include
    - lib
    - share
    - /usr/local/lib
# command to install dependencies
install:
  - "make deploy"
# command to run tests
script: "make test-coverage-travis-ci" #nosetests
after_success:
  - "make test-coveralls"
